[package]
name = "pymol-session"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "PSE session file reader for pymol-rs"

[dependencies]
ahash.workspace = true
flate2.workspace = true
thiserror.workspace = true
pymol-scene.workspace = true
pymol-mol.workspace = true
pymol-settings.workspace = true
pymol-color.workspace = true
lin_alg.workspace = true
log.workspace = true
serde = { workspace = true }
rmp-serde.workspace = true
